WARNING 2024-12-04 14:40:33,386 log Not Found: /api/sent-form/1/1/
WARNING 2024-12-04 14:40:33,388 basehttp "GET /api/sent-form/1/1/ HTTP/1.1" 404 5368
WARNING 2024-12-04 14:53:46,550 log Not Found: /api/sent-form/
WARNING 2024-12-04 14:53:46,553 basehttp "GET /api/sent-form/ HTTP/1.1" 404 4242
WARNING 2024-12-04 14:57:06,260 log Not Found: /api/sent-form/200/10869/
WARNING 2024-12-04 14:57:06,261 basehttp "GET /api/sent-form/200/10869/ HTTP/1.1" 404 5404
WARNING 2024-12-04 15:03:20,392 log Not Found: /api/sent-form/1/1/
WARNING 2024-12-04 15:03:20,393 basehttp "GET /api/sent-form/1/1/ HTTP/1.1" 404 5368
WARNING 2024-12-04 15:04:50,398 log Not Found: /api/sent-form/1/1/
WARNING 2024-12-04 15:04:50,401 basehttp "GET /api/sent-form/1/1/ HTTP/1.1" 404 5368
ERROR 2024-12-04 15:09:13,841 log Internal Server Error: /api/sent-form/1/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/core/api/views.py", line 32, in get
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 571, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 523, in to_representation
    for field in fields:
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 1079, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/rest_framework/serializers.py", line 1175, in get_field_names
    assert field_name in fields, (
           ^^^^^^^^^^^^^^^^^^^^
AssertionError: The field 'email_questions' was declared on serializer SentFormSerializer, but has not been included in the 'fields' option.
ERROR 2024-12-04 15:09:13,844 basehttp "GET /api/sent-form/1/1/ HTTP/1.1" 500 130981
WARNING 2024-12-04 16:13:40,409 log Not Found: /api/sent-form/1/3/
WARNING 2024-12-04 16:13:40,410 basehttp "GET /api/sent-form/1/3/ HTTP/1.1" 404 5368
